### PR TITLE
using try_receive instead of receive for TRB

### LINKED ISSUE #186: TRB very inefficient with exceptions
The loop in the TRB is controlled by a number of receive calls that have 0 timeout. 
Due to what has been discussed yesterday, this is far from optimal. 
Since we now have dedicated methods to solve this, we should use them

### PR DESCRIPTION
**Pull request by mroda88**
this solves issue #186

### CODE REVIEW

File: plugins/TriggerRecordBuilder.cpp [hunk 1]
```diff
@@ -370,17 +370,20 @@ TriggerRecordBuilder::read_fragments()
...
+      ers::error(e);
       continue ;
     }
 
+    if ( ! temp_fragment ) continue ;
+    
     new_fragments = true;
     
-    TriggerId temp_id(*temp_fragment);
+    TriggerId temp_id(**temp_fragment);
```
Comment (eflumerf) [inline plugins/TriggerRecordBuilder.cpp]: Use .value() to dereference std::optional

**Review by eflumerf — APPROVED** [review]
LGTM, builds and doesn't make the integration tests *worse*
